---
name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pretend to run tests
        run: |
          echo 'Running tests... all OK'

  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }} # e.g. v1.0.0
      version: ${{ steps.release-please.outputs.version }} # e.g. 1.0.0
      prs: ${{ steps.release-please.outputs.prs }}
      all: ${{ toJSON(steps.release-please.outputs) }}
    steps:
      - uses: jimeh/release-please-manifest-action@v1
        id: release-please
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

  # Always runs after release-please to print all the outputs.
  debug:
    runs-on: ubuntu-latest
    needs: [release-please]
    steps:
      - name: Print all
        run: |
          echo '${{ needs.release-please.outputs.all }}' | jq

  # Only runs if a Release Pull Request was created by release-please.
  debug-release-pr:
    runs-on: ubuntu-latest
    needs: [release-please]
    if: needs.release-please.outputs.prs
    steps:
      - name: Print PRs
        run: |
          echo '${{ needs.release-please.outputs.prs }}' | jq

  # Only runs if a release was created by release-please.
  debug-release:
    runs-on: ubuntu-latest
    needs: [release-please, test]
    if: needs.release-please.outputs.release_created
    steps:
      # Examples of how to access the outputs from the release-please job, so
      # they can be used to build any assets/artifacts for the release.
      - name: Print release info
        run: |
          echo "Release created: ${{ needs.release-please.outputs.release_created }}"
          echo "Tag name: ${{ needs.release-please.outputs.tag_name }}"
          echo "Version: ${{ needs.release-please.outputs.version }}"
