---
on: push

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }} # e.g. v1.0.0
      version: ${{ steps.release-please.outputs.version }} # e.g. 1.0.0
      prs: ${{ steps.release-please.outputs.prs }}
      all: ${{ toJSON(steps.release-please.outputs) }}
    steps:
      - uses: jimeh/release-please-action@alpha
        id: release-please
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
          command: manifest

  debug:
    runs-on: ubuntu-latest
    needs: [release-please]
    steps:
      - name: Print all
        run: |
          echo '${{ needs.release-please.outputs.all }}' | jq
